### ISSUE TITLE
demo11 Hook/react-use

### ISSUE THREAD

**Issue by lizi333** [feihub/react-demo#18]

**Comment by feihub** [comment]
useReducer
useRef
useImperativeHandle
useLayoutEffect
useDebugValue

**Comment by feihub** [comment]
useCallback
返回一个 memoized 回调函数。
useCallback其实是利用memoize减少不必要的子组件重新渲染

useMemo
返回一个 memoized 值。
有助于避免在每次渲染时都进行高开销的计算

useImperativeHandle
通过useImperativeHandle可以只暴露特定的操作
减少暴露给父组件获取的DOM元素属性, 只暴露给父组件需要用到的DOM方法


useLayoutEffect
这个是用在处理DOM的时候,当你的useEffect里面的操作需要处理DOM,
并且会改变页面的样式,就需要用这个,否则可能会出现出现闪屏问题, 
useLayoutEffect里面的callback函数会在DOM更新完成后立即执行,
但是会在浏览器进行任何绘制之前运行完成,阻塞了浏览器的绘制.

**Comment by feihub** [comment]
https://github.com/streamich/react-use

https://blog.csdn.net/weixin_39371152/article/details/105082638
